apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  workspaces:
    - name: myworkspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: myworkspace
      params:
        - name: url
          value: git@github.com:cjmateos/tektonpoc.git
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      params:
        - name: IMAGE
          value: docker.io/cjmateos/tektonpoc
        - name: IMAGE_PUSH_SECRET_NAME
          value: image-push-secrets
      workspaces:
        - name: source
          workspace: myworkspace
